Header: main places
kudryavtseva99/Travel-Landing-Page pull request #4
Opened 2023-09-05 11:02 UTC by kudryavtseva99

2023-09-17 14:03 UTC, artur-barmin requested changes

2023-09-17 14:03 UTC, artur-barmin-ocl commented on index.html
> +        <div class="wrapper-full">
why this class is named so different from "places"? I'm not strong in CSS metodologies, let's take BEM (block-element-modificator). Each block can have elements, and each element should reflect its relation to the parent block - for example, block "places" would have element "places_header".
What metodology do we use in this project?

UPD: ah ok, I see, you're using BEM. And "wrapper-full" is standalone block, which doesn't care about its content, that's why we don't see his name in the other classes

2023-09-17 14:03 UTC, artur-barmin-ocl commented on CSS/style.css
> +  margin-bottom: 139px;
why do you use absolute values for sizing? Will layout made of this adapt to different screens?

2023-09-17 14:03 UTC, artur-barmin-ocl commented on index.html
> +                <img src="/img/tour-1.jpg" alt="Prefecture in Focus: Tottori" class="tour_thumb">
why don't you use `figure` here?

2023-09-17 14:03 UTC, artur-barmin-ocl commented on CSS/style.css
> +  grid-gap: 57px;
I don't really like absolute values for sizing. Just imagine, what if we change base font size for whole page, what will happen? Everything is set with pixels. We increase font size -> text content takes more space now, it will break the layout. We'll be forced to change every absolute value in the CSS, **every value**

To solve described problem, we have a lot of solutions. For example couple of them:
- use rem/em. If we change base font size, it will be taken as base value and will be decreased/increased accordingly
- use CSS-variables. I'm not sure how modern browsers support this feature, we can check it on [Can I use](https://caniuse.com/). This way we can create variables like "#fontSize: 14px" and use it everywhere: .top_place: {fontSize: #fontSize}. If we'll change something in our CSS, we can change only the value of variable

I guess, we can leave it as is for next pull requests

2023-09-17 14:03 UTC, artur-barmin-ocl commented on CSS/style.css
> +}
For me, it's better to split the "logic". Here we have 2 things in .header class: view and behavior. View describes "how it should look like", behavior is about "how it should move".
We can split this block into 2 separate ones:
.header {view rules}
.header {rules related to animation - transition and rules which will be changed during the animation}

It will increase readability of your code

2023-09-17 14:03 UTC, artur-barmin-ocl commented on main.js
> +        }
Let's get rid of onscroll attribure and use addEventListener instead:
1) create separate function that toggles classes
2) and pass it in window.addEventListener

2023-09-17 14:03 UTC, artur-barmin commented on index.html
> +      <div class="wrapper">
wrapper, not wrapper-full?

2023-09-18 15:36 UTC, kudryavtseva99 commented on index.html
> +                <img src="/img/tour-1.jpg" alt="Prefecture in Focus: Tottori" class="tour_thumb">
We didn't use this tag because it is used when the image has a title, and here is the description of its name

2023-09-18 15:53 UTC, kudryavtseva99 commented on index.html
> +                <img src="/img/tour-1.jpg" alt="Prefecture in Focus: Tottori" class="tour_thumb">
If I understood everything correctly

2023-09-18 16:13 UTC, kudryavtseva99 commented on main.js
> +        }
I've remade it, you can check it out

2023-09-18 16:24 UTC, artur-barmin approved these changes

2023-09-18 16:24 UTC, merged